name: Integration Tests
on:
  workflow_dispatch:
    inputs:
      gitTag:
        description: 'Tag version (e. 1.1.6)'
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Clone integration tests
      run: |
        git clone git@github.com:cto-ai/sdk-integration-testing.git
    - name: Docker Build
      run: |
        docker build --build-arg SDK_TAG=v${{github.event.inputs.gitTag}} -f sdk-integration-testing/Dockerfile sdk-integration-testing
