name: Integration Tests
on:
  workflow_dispatch:
    inputs:
      gitTag:
        description: 'Tag version (e. 1.1.6)'
        required: true

env:
  CI_USER: ${{ secrets.CI_USER }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Clone integration tests
      run: |
        git config --global url."https://${{ secrets.CTO_PAT }}@github.com/cto-ai".insteadOf "https://github.com/cto-ai"
        cat ~/.gitconfig
        git config --global user.email "ops@cto.ai"
        git config --global user.name "$CI_USER"
        git clone git@github.com:cto-ai/sdk-integration-testing.git
    - name: Docker Build
      run: |
        docker build --build-arg SDK_TAG=v${{github.event.inputs.gitTag}} -f sdk-integration-testing/Dockerfile sdk-integration-testing
